# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
xcode_project: CuteClock.xcodeproj
xcode_scheme: CuteClock

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

# support carthage cache
cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
  
script:
- xcodebuild -project CuteClock.xcodeproj -target CuteClock -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
# - pod lib lint

